### ISSUE TITLE
Standardise empty lines at the beginning and end of a class

### ISSUE THREAD

**Issue by marcuspang** [AY2223S1-CS2103T-W13-4/tp#105]
Currently, adding a space at the start/end of a class is not standardised. 

```java
class Example {

    // ^ empty line at start of class

    // fields, methods, nested classes, ...

    // v empty line at end of class

}
```

We should remove all instances of these empty lines, which can be enforced in `checkstyle.xml`. See https://github.com/checkstyle/checkstyle/issues/3379

**Comment by Devanshshah1309** [comment]
Not very important as of now.

**Comment by mjgui** [comment]
Closing as unimportant
