### ISSUE TITLE
Handle non-alphanumeric team names

### ISSUE THREAD

**Issue by Devanshshah1309** [AY2223S1-CS2103T-W13-4/tp#118]
Currently, the program crashes for non-alphanumeric team names and there's no error message displayed to the user.

**Comment by marcuspang** [comment]
Other `Name` classes should also handle non-alphanumeric characters like `/` for (e.g. `somebody s/o person`)

**Comment by marcuspang** [comment]
Note, the `TruthTableParser` currently parses `a'a'a` as `aaa` which is unintentional
