### ISSUE TITLE
[PE-D][Tester B] Minor UI inconvenience

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W13-4/tp#131]
Really like the use of command line style help messages, but it is really hard to read with the message area being very small.

For e.g., `add person --help` returns a really long help message, it's quite hard to read it.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: gunbux/ped#1

**Comment by Devanshshah1309** [comment]
I don't think we can do much about this right now anyway so feel free to close it if you feel the same way.
