### ISSUE TITLE
[PE-D][Tester A] Program exited for typing some commands not shown in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W13-4/tp#159]
Problem: Program exited for typing some commands not shown in User Guide such as `ex`.

![image.png](https://raw.githubusercontent.com/LianGuoYang/ped/main/files/4cc0371a-448b-4330-932a-810d75d8dcb9.png)

![image.png](https://raw.githubusercontent.com/LianGuoYang/ped/main/files/1a87f09f-bbb8-4b91-9bc6-15b8362d7b68.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: LianGuoYang/ped#17

**Comment by Devanshshah1309** [comment]
@marcuspang Reminder to include aliases for all commands in the UG. Can close this issue whenever it's done.

**Comment by mjgui** [comment]
Closing first, subsumed under #84
