### ISSUE TITLE
[PE-D][Tester A] Unclear UG for Find members : find member

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W13-4/tp#162]
Problem: UG said that can find by name or email but didnt specify not both at the same time.

![image.png](https://raw.githubusercontent.com/LianGuoYang/ped/main/files/3f6abdef-fafb-421f-83de-2d94a91e4aad.png)

![image.png](https://raw.githubusercontent.com/LianGuoYang/ped/main/files/a124ad3c-a941-4301-be27-91263c0c7918.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: LianGuoYang/ped#18

**Comment by Devanshshah1309** [comment]
This should have been fixed by #128 (@marcuspang feel free to close this issue if it has been solved)
