### ISSUE TITLE
[PE-D][Tester D] Tasks with deleted members previously assigned will have an existing member assigned to them.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W13-4/tp#166]
For example, after assigning 3 members to a task and then deleting the 3 members from the team, the task will be automatically assigned the first remaining member in the team. By right the task should have 0 people assigned to it. To recreate this bug, follow these steps: create a new team, add the first 4 contacts to the team, add a new task, assign the first 3 members to the task, delete the first 3 members from the team, change the description of the task. It will show that the task has been assigned to the remaining member.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: pewggls/ped#8

**Comment by mjgui** [comment]
Cannot replicate
