### ISSUE TITLE
Inconsistent help messages

### ISSUE THREAD

**Issue by marcuspang** [AY2223S1-CS2103T-W13-4/tp#193]
Variable names in `Command` classes are different even with the same type.

For instance,  the `add member` command where the help message says `<targetPersonIndex>` but our UG says `PersonIndex`

**Comment by marcuspang** [comment]
Also, we can think about using abbreviated synopsis messages if the command syntax is confusing

See https://picocli.info/#_abbreviated_synopsis

**Comment by Devanshshah1309** [comment]
> Also, we can think about using abbreviated synopsis messages if the command syntax is confusing
> 
> See https://picocli.info/#_abbreviated_synopsis

Hmm so the abbreviations will only be available in the user guide? Not sure if people might see that as an inconsistency

**Comment by Devanshshah1309** [comment]
Also, I can change `targetPersonIndex` to `personIndex` but not `PersonIndex` (coz of Java variable naming conventions). Do you think that should be okay?
