### ISSUE TITLE
Improve UG for 2101

### ISSUE THREAD

**Issue by marcuspang** [AY2223S1-CS2103T-W13-4/tp#218]
See #84 and #175

### Grading Criteria

Checkout the detailed grading criteria at the bottom of the [team docs](https://docs.google.com/document/d/1gxF8srtl0hBqOaG1Du9au6K5xXwtAlRC4U777IqdPcI/edit#)

### Tasks
Just make sure you do everything the grading criteria requires us to do.
- [ ] Front Matters
- [ ] Instructions
- [ ] Presentation
- [ ] Language, style and tone
- [ ] Overall

PS. I've texted Ms. Serene on whether we can split by rubrics instead of sections to make the UG's tone consistent across sections.

**Comment by Devanshshah1309** [comment]
Need to wait 1 more day before we can push code (as per instructions on CS2103T website) right? - and while doing this, we shouldn't touch any part of the code other than the `docs` and `images` folder.
