### ISSUE TITLE
`Team` objects in address book are not immutable

### ISSUE THREAD

**Issue by marcuspang** [AY2223S1-CS2103T-W13-4/tp#25]
See #21 for more details on how the `Team` model is introduced.

This is a concern when conducting tests for `Team` objects, as we are not cloning the `Team` object with a new `ModelManager`. Ideally, once we are able to "set" our current teams, we will have a better way to manage the `Team`s inside the address book.

For example, the following test will not work (taken from `DeleteCommandTest`)

```java

@Test
public void execute_validIndexFilteredList_success() {
    showPersonAtIndex(model, INDEX_FIRST_PERSON);

    Person personToAdd = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());
    AddMemberCommand addMemberCommand = new AddMemberCommand(INDEX_FIRST_PERSON);

    String expectedMessage = String.format(AddMemberCommand.MESSAGE_ADD_MEMBER_SUCCESS, personToAdd);

    Model expectedModel = new ModelManager(model.getAddressBook(), new UserPrefs());
    expectedModel.getTeam().addMember(personToAdd);
    showNoPerson(expectedModel);

    assertCommandSuccess(addMemberCommand, model, expectedMessage, expectedModel);
}
```

**Comment by Devanshshah1309** [comment]
@ling-ui @changjy44 might be important for you to note this when you're writing tests.
