### ISSUE TITLE
Update UG 

### ISSUE THREAD

**Issue by mjgui** [AY2223S1-CS2103T-W13-4/tp#84]
~~Our UG is currently missing the commands originally from AB3 e.g. `add`, `list`~~

~~We should do a look through and clean this up after @marcuspang is done with transplanting picocli~~

**Comment by marcuspang** [comment]
For the commands, we should mention both the short and long version of flags in the usage and examples

**Comment by marcuspang** [comment]
Add sort commands

**Comment by marcuspang** [comment]
- Update the command summary table (and potentially move it to the top)
- Add hyperlinks to navigate around the document
- Improve the language at the top of the User Guide
- Improve based on CS2101 feedback
- Add aliases for all commands (#159)
- Command summary (#155)
- We should stress that quotes are not necessary for date time fields at the top, many of the issues stem from this inconsistency with other fields

**Comment by marcuspang** [comment]
Glossary
- arguments/parameters (standardise)
- flags
- command
- home folder

**Comment by marcuspang** [comment]
Add meaningful example sections
- “Onboarding your team”
- “Migrating your team to TruthTable”

Beginners
- Tutorial sections

Advanced users
- reference command

**Comment by marcuspang** [comment]
Relevant: https://github.com/AY2223S1-CS2103T-W13-4/tp/issues/86

Add summary to the top along with some FAQs

**Comment by marcuspang** [comment]
Improve description to match use case?

**Comment by Devanshshah1309** [comment]
Ensure that all the issues raised by our peer reviewers in 2101 are also fixed - they bring up some very good points. 

Link to the reviews is: https://drive.google.com/drive/folders/12lxZrnK3KE-vdl7-Xjw1gyxliwDI9Llq?usp=share_link

**Comment by Devanshshah1309** [comment]
Feedback from Ms. Serene:
- [ ] Purpose of UG - Target audience.
- [ ] Explain main features of app.
- [ ] How to use this guide? How to navigate this guide?
- [ ] Label the different parts of the GUI (red boxes + arrows).
- [ ] Explain more about CLI for people with no experience.
- [ ] Table of contents.
- [ ] Improve navigability within the UG.
- [ ] Build a narrative that explains the flow of the UG - make it a story!
- [ ] Include hyperlinks to `git` and `docker` in the message
- [ ] Include preamble for each of the command sets (e.g. command to manage teams, tasks, etc.)
- [ ] Give high-level view before the low-level details
- [ ] Examples in UG must match the sample data in TruthTable (e.g. names should match)
- [ ] Boost confidence of the user ("Well done! We're halfway there :)" "Good job! You know now how to manage tasks")
- [ ] Include "Warnings", "Tips", and "Important notes"
- [ ] Change font-size + font family + layout to improve readability.
- [ ] Include more visuals of examples of commands - maybe for each command set.
- [ ] Include case study, examples to enhance user understanding.
- [ ] Overall tone of the UG should be friendly and motivating.

**Comment by mjgui** [comment]
- [ ] For each numbered diagram, it'll be nice if the numbers in the table are colour coordinated also
![image](https://user-images.githubusercontent.com/9080115/200115181-09182eea-1a54-44bb-959c-f106512ede5d.png)

- [ ] Help message should hyperlink to section on how to understand the help message
![image](https://user-images.githubusercontent.com/9080115/200115203-8c0892da-4ee3-4d5f-8054-b7300ae433a3.png)
