### ISSUE TITLE
Inconsistent behaviour: `list_members` vs `list_tasks`

### ISSUE THREAD

**Issue by Devanshshah1309** [AY2223S1-CS2103T-W13-4/tp#99]
I think `list_members` should also just display the members in the result display instead of updating the right panel (`personList`) to make it consistent with `list_tasks`.

**Comment by mjgui** [comment]
btw it's also possible for us to just delete all the list commands (both `list_tasks` and `list_members`)

**Comment by mjgui** [comment]
Closed by #100
